-- Catalog seed: products + primary product_images.
-- GENERATED by database/seed/generate_catalog_seed.py from backend/datasets/catalog/metadata.csv.
-- Do not edit by hand; change the CSV and regenerate. Safe to run repeatedly (upserts).
-- description and availability are left NULL: the catalog has no verified values for them.
-- Products: 50

BEGIN;

-- b2s_1092466
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1092466', 'ปากกาลูกลื่น Monami รุ่น ฟลิป สีเขียวพาสเทล ขนาด 0.7 มม.', 'ballpoint_pen', 'Monami', '{"category_th": "ปากกาลูกลื่น", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1092466.jpg"}'::jsonb, 79.00, 'THB', 'https://www.b2s.co.th/product/ปากกาลูกลื่น-monami-รุ่น-ฟลิป-สีเขียวพาสเทล-ขนาด-0-7-มม-p.1092466')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1092466') AND storage_key <> 'catalog/ballpoint_pen/monami_flip_07_pastel_green.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/ballpoint_pen/monami_flip_07_pastel_green.jpg', true, 'ปากกาลูกลื่น Monami รุ่น ฟลิป สีเขียวพาสเทล ขนาด 0.7 มม.' FROM products WHERE sku = 'b2s_1092466'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1092374
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1092374', 'ปากกาลูกลื่น PENTEL รุ่น Feel-it ขนาด 0.7 มม.ด้ามส้มหมึกน้ำเงิน', 'ballpoint_pen', 'Pentel', '{"category_th": "ปากกาลูกลื่น", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1092374.jpg"}'::jsonb, 10.00, 'THB', 'https://www.b2s.co.th/product/ปากกาลูกลื่น-pentel-รุ่น-feel-it-ขนาด-0-7-มม-ด้ามส้มหมึกน้ำเงิน-p.1092374')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1092374') AND storage_key <> 'catalog/ballpoint_pen/pentel_feelit_07_orange_blue.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/ballpoint_pen/pentel_feelit_07_orange_blue.jpg', true, 'ปากกาลูกลื่น PENTEL รุ่น Feel-it ขนาด 0.7 มม.ด้ามส้มหมึกน้ำเงิน' FROM products WHERE sku = 'b2s_1092374'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1091933
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1091933', 'PENTEL ปากกาเจล รุ่น Energel Hexagon BL667 สีน้ำเงิน ขนาด 0.7 มม.', 'gel_pen', 'Pentel', '{"catalog_note": "ราคา 590 น่าจะเป็นต่อกล่อง ควรตรวจสอบ", "category_th": "ปากกาเจล", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1091933.jpg"}'::jsonb, 590.00, 'THB', 'https://www.b2s.co.th/product/pentel-ปากกาเจล-รุ่น-energel-hexagon-bl667-สีน้ำเงิน-ขนาด-0-7-มม-p.1091933')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1091933') AND storage_key <> 'catalog/gel_pen/pentel_energel_hexagon_bl667_07_blue.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/gel_pen/pentel_energel_hexagon_bl667_07_blue.jpg', true, 'PENTEL ปากกาเจล รุ่น Energel Hexagon BL667 สีน้ำเงิน ขนาด 0.7 มม.' FROM products WHERE sku = 'b2s_1091933'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1092448
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1092448', 'ปากกาเจล Uni รุ่น UMN-S-38 สีม่วง ขนาด 0.38 มม.', 'gel_pen', 'Uni', '{"category_th": "ปากกาเจล", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1092448.jpg"}'::jsonb, 42.00, 'THB', 'https://www.b2s.co.th/product/ปากกาเจล-uni-รุ่น-umn-s-38-สีม่วง-ขนาด-0-38-มม-p.1092448')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1092448') AND storage_key <> 'catalog/gel_pen/uni_umn_s_38_purple.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/gel_pen/uni_umn_s_38_purple.jpg', true, 'ปากกาเจล Uni รุ่น UMN-S-38 สีม่วง ขนาด 0.38 มม.' FROM products WHERE sku = 'b2s_1092448'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1003680
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1003680', 'ปากกาเน้นข้อความ 2 หัว (ชุด5สี) จาวา Duplex', 'highlighter', 'Java', '{"category_th": "ปากกาเน้นข้อความ", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1003680.jpg"}'::jsonb, 100.00, 'THB', 'https://www.b2s.co.th/product/ปากกาเน้นข้อความ-2-หัว-ชุด5สี-จาวา-duplex-p.1003680')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1003680') AND storage_key <> 'catalog/highlighter/java_duplex_highlighter_5colors.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/highlighter/java_duplex_highlighter_5colors.jpg', true, 'ปากกาเน้นข้อความ 2 หัว (ชุด5สี) จาวา Duplex' FROM products WHERE sku = 'b2s_1003680'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1009200
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1009200', 'ปากกาเน้นข้อความ โมนามิ x2218049900 604 คละสี (4ด้าม)', 'highlighter', 'Monami', '{"category_th": "ปากกาเน้นข้อความ", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1009200.jpg"}'::jsonb, 98.00, 'THB', 'https://www.b2s.co.th/product/ปากกาเน้นข้อความ-โมนามิ-x2218049900-604-คละสี-4ด้าม-p.1009200')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1009200') AND storage_key <> 'catalog/highlighter/monami_604_highlighter_4pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/highlighter/monami_604_highlighter_4pack.jpg', true, 'ปากกาเน้นข้อความ โมนามิ x2218049900 604 คละสี (4ด้าม)' FROM products WHERE sku = 'b2s_1009200'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1000785
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1000785', 'HORSE ปากกามาร์คเกอร์ รุ่น 2 หัว คละสี (แพ็ค 3 ด้าม)', 'marker', 'Horse', '{"category_th": "ปากกามาร์คเกอร์", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1000785.jpg"}'::jsonb, 53.00, 'THB', 'https://www.b2s.co.th/product/ปากกามาร์คเกอร์-2-หัว-ตราม้า-คละสี-แพ็ค-3-ด้าม-p.1000785')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1000785') AND storage_key <> 'catalog/marker/horse_twin_marker_3pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/marker/horse_twin_marker_3pack.jpg', true, 'HORSE ปากกามาร์คเกอร์ รุ่น 2 หัว คละสี (แพ็ค 3 ด้าม)' FROM products WHERE sku = 'b2s_1000785'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1008913
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1008913', 'ปากกามาร์คเกอร์ Accu Liner 0.7มม.นง. โมนามิ X10401202X0', 'marker', 'Monami', '{"catalog_note": "ปากกาหัวเข็ม (fineliner) แต่ B2S จัดเป็นปากกามาร์กเกอร์", "category_th": "ปากกามาร์คเกอร์", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1008913.jpg"}'::jsonb, 20.00, 'THB', 'https://www.b2s.co.th/product/ปากกามาร์คเกอร์-accu-liner-0-7มม-นง-โมนามิ-x10401202x0-p.1008913')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1008913') AND storage_key <> 'catalog/marker/monami_accu_liner_07_blue.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/marker/monami_accu_liner_07_blue.jpg', true, 'ปากกามาร์คเกอร์ Accu Liner 0.7มม.นง. โมนามิ X10401202X0' FROM products WHERE sku = 'b2s_1008913'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1092492
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1092492', 'ปากกามาร์คเกอร์ PENTEL  Permanent แบบ2หัว สีแดง', 'marker', 'Pentel', '{"category_th": "ปากกามาร์คเกอร์", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1092492.jpg"}'::jsonb, 33.00, 'THB', 'https://www.b2s.co.th/product/ปากกามาร์คเกอร์-pentel-permanent-แบบ2หัว-สีแดง-p.1092492')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1092492') AND storage_key <> 'catalog/marker/pentel_permanent_twin_marker_red.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/marker/pentel_permanent_twin_marker_red.jpg', true, 'ปากกามาร์คเกอร์ PENTEL  Permanent แบบ2หัว สีแดง' FROM products WHERE sku = 'b2s_1092492'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1092007
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1092007', 'ปากกาไวท์บอร์ด FABER CASTELL สีแดง', 'whiteboard_marker', 'Faber-Castell', '{"category_th": "ปากกาไวท์บอร์ด", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1092007.jpg"}'::jsonb, 26.00, 'THB', 'https://www.b2s.co.th/product/ปากกาไวท์บอร์ด-faber-castell-สีแดง-p.1092007')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1092007') AND storage_key <> 'catalog/whiteboard_marker/fabercastell_whiteboard_marker_red.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/whiteboard_marker/fabercastell_whiteboard_marker_red.jpg', true, 'ปากกาไวท์บอร์ด FABER CASTELL สีแดง' FROM products WHERE sku = 'b2s_1092007'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1000920
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1000920', 'HORSE ปากกาไวท์บอร์ด รุ่น H-22 สีน้ำเงิน ขนาด 2 มม. (แพ็ค 3 ด้าม)', 'whiteboard_marker', 'Horse', '{"category_th": "ปากกาไวท์บอร์ด", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1000920.jpg"}'::jsonb, 45.00, 'THB', 'https://www.b2s.co.th/product/ปากกาไวท์บอร์ด-ตราม้า-h-22-น้ำเงิน-แพ็ค-3-ด้าม-p.1000920')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1000920') AND storage_key <> 'catalog/whiteboard_marker/horse_h22_whiteboard_marker_blue_3pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/whiteboard_marker/horse_h22_whiteboard_marker_blue_3pack.jpg', true, 'HORSE ปากกาไวท์บอร์ด รุ่น H-22 สีน้ำเงิน ขนาด 2 มม. (แพ็ค 3 ด้าม)' FROM products WHERE sku = 'b2s_1000920'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1005836
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1005836', 'ปากกาไวท์บอร์ด 15386A 2 มม. ส้ม โมนามิ PI-220', 'whiteboard_marker', 'Monami', '{"category_th": "ปากกาไวท์บอร์ด", "group": "ปากกาและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1005836.jpg"}'::jsonb, 28.00, 'THB', 'https://www.b2s.co.th/product/ปากกาไวท์บอร์ด-15386a-2-มม-ส้ม-โมนามิ-pi-220-p.1005836')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1005836') AND storage_key <> 'catalog/whiteboard_marker/monami_pi220_whiteboard_marker_orange.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/whiteboard_marker/monami_pi220_whiteboard_marker_orange.jpg', true, 'ปากกาไวท์บอร์ด 15386A 2 มม. ส้ม โมนามิ PI-220' FROM products WHERE sku = 'b2s_1005836'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1009802
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1009802', 'ชุดดินสอกด 0.5มม. ฟ้า (แพ็ค2ชิ้น) เพนเทล AX105-CWBP', 'mechanical_pencil', 'Pentel', '{"category_th": "ดินสอกด", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1009802.jpg"}'::jsonb, 33.00, 'THB', 'https://www.b2s.co.th/product/ชุดดินสอกด-0-5มม-ฟ้า-แพ็ค2ชิ้น-เพนเทล-ax105-cwbp-p.1009802')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1009802') AND storage_key <> 'catalog/mechanical_pencil/pentel_ax105_cwbp_05_blue_2pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/mechanical_pencil/pentel_ax105_cwbp_05_blue_2pack.jpg', true, 'ชุดดินสอกด 0.5มม. ฟ้า (แพ็ค2ชิ้น) เพนเทล AX105-CWBP' FROM products WHERE sku = 'b2s_1009802'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1010208
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1010208', 'ชุดดินสอกด 0.5 มม. Rotring Tikky สีดำ (2ชิ้น/แพ็ค)', 'mechanical_pencil', 'Rotring', '{"category_th": "ดินสอกด", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1010208.jpg"}'::jsonb, 140.00, 'THB', 'https://www.b2s.co.th/product/ชุดดินสอกด-0-5-มม-rotring-tikky-สีดำ-2ชิ้น-แพ็ค-p.1010208')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1010208') AND storage_key <> 'catalog/mechanical_pencil/rotring_tikky_05_black_2pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/mechanical_pencil/rotring_tikky_05_black_2pack.jpg', true, 'ชุดดินสอกด 0.5 มม. Rotring Tikky สีดำ (2ชิ้น/แพ็ค)' FROM products WHERE sku = 'b2s_1010208'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1091236
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1091236', 'เครื่องเหลาดินสอปรับได้  ELM S-221-BK', 'sharpener', 'ELM', '{"category_th": "กบเหลาดินสอ", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1091236.jpg"}'::jsonb, 339.00, 'THB', 'https://www.b2s.co.th/product/เครื่องเหลาดินสอปรับได้-elm-s-221-bk-p.1091236')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1091236') AND storage_key <> 'catalog/sharpener/elm_s221_pencil_sharpener_machine.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/sharpener/elm_s221_pencil_sharpener_machine.jpg', true, 'เครื่องเหลาดินสอปรับได้  ELM S-221-BK' FROM products WHERE sku = 'b2s_1091236'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1005909
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1005909', 'กบเหลาดินสอ Clock Clock คละสี มาเพ็ด SH017610', 'sharpener', 'Maped', '{"category_th": "กบเหลาดินสอ", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1005909.jpg"}'::jsonb, 66.00, 'THB', 'https://www.b2s.co.th/product/กบเหลาดินสอ-clock-clock-คละสี-มาเพ็ด-sh017610-p.1005909')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1005909') AND storage_key <> 'catalog/sharpener/maped_clock_sharpener.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/sharpener/maped_clock_sharpener.jpg', true, 'กบเหลาดินสอ Clock Clock คละสี มาเพ็ด SH017610' FROM products WHERE sku = 'b2s_1005909'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1093329
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1093329', 'ME.STYLE  กบเหลาดินสอ 1 รู ลายสตอเบอร์ รุ่น STRAWBERRY', 'sharpener', 'ME.STYLE', '{"category_th": "กบเหลาดินสอ", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1093329.jpg"}'::jsonb, 19.00, 'THB', 'https://www.b2s.co.th/product/me-style-กบเหลาดินสอ-1-รู-ลายสตอเบอร์-รุ่น-strawberry-p.1093329')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1093329') AND storage_key <> 'catalog/sharpener/mestyle_strawberry_sharpener_1hole.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/sharpener/mestyle_strawberry_sharpener_1hole.jpg', true, 'ME.STYLE  กบเหลาดินสอ 1 รู ลายสตอเบอร์ รุ่น STRAWBERRY' FROM products WHERE sku = 'b2s_1093329'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1093288
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1093288', 'กระเป๋าดินสอ 21 x 14ซม. BELLA 1-A', 'pencil_case', 'BELLA', '{"category_th": "กระเป๋าดินสอ", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1093288.jpg"}'::jsonb, 149.00, 'THB', 'https://www.b2s.co.th/product/กระเป๋าดินสอ-21-x-14ซม-bella-1-a-p.1093288')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1093288') AND storage_key <> 'catalog/pencil_case/bella_pencil_pouch_1a.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/pencil_case/bella_pencil_pouch_1a.jpg', true, 'กระเป๋าดินสอ 21 x 14ซม. BELLA 1-A' FROM products WHERE sku = 'b2s_1093288'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1007615
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1007615', 'กระเป๋าดินสอ คละสี อี-ไฟล์ CPK32', 'pencil_case', 'e-file', '{"category_th": "กระเป๋าดินสอ", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1007615.jpg"}'::jsonb, 135.00, 'THB', 'https://www.b2s.co.th/product/กระเป๋าดินสอ-คละสี-อี-ไฟล์-cpk32-p.1007615')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1007615') AND storage_key <> 'catalog/pencil_case/efile_cpk32_pencil_pouch.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/pencil_case/efile_cpk32_pencil_pouch.jpg', true, 'กระเป๋าดินสอ คละสี อี-ไฟล์ CPK32' FROM products WHERE sku = 'b2s_1007615'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1093326
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1093326', 'กระเป๋าดินสอ 1 ME.STYLE STRAWBERRY 20.5x6 ซม.', 'pencil_case', 'ME.STYLE', '{"category_th": "กระเป๋าดินสอ", "group": "ดินสอและอุปกรณ์เสริม", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1093326.jpg"}'::jsonb, 149.00, 'THB', 'https://www.b2s.co.th/product/กระเป๋าดินสอ-1-me-style-strawberry-20-5x6-ซม-p.1093326')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1093326') AND storage_key <> 'catalog/pencil_case/mestyle_strawberry_pencil_pouch_1.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/pencil_case/mestyle_strawberry_pencil_pouch_1.jpg', true, 'กระเป๋าดินสอ 1 ME.STYLE STRAWBERRY 20.5x6 ซม.' FROM products WHERE sku = 'b2s_1093326'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K092470
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K092470', 'ยางลบพร้อมแปรง Montmarte 2 แท่ง', 'eraser', 'Mont Marte', '{"category_th": "ยางลบ", "group": "ยางลบและน้ำยาลบคำผิด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K092470.jpg"}'::jsonb, 84.00, 'THB', 'https://www.b2s.co.th/product/ยางลบพร้อมแปรง-montmarte-2-แท่ง-p.K092470')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K092470') AND storage_key <> 'catalog/eraser/montmarte_eraser_brush_2pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/eraser/montmarte_eraser_brush_2pack.jpg', true, 'ยางลบพร้อมแปรง Montmarte 2 แท่ง' FROM products WHERE sku = 'b2s_K092470'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1008290
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1008290', 'ยางลบดินสอ (2 ก้อน/แพ็ค) เพนเทล Hi-Polymer ZES-08', 'eraser', 'Pentel', '{"category_th": "ยางลบ", "group": "ยางลบและน้ำยาลบคำผิด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1008290.jpg"}'::jsonb, 40.00, 'THB', 'https://www.b2s.co.th/product/ยางลบดินสอ-2-ก้อน-แพ็ค-เพนเทล-hi-polymer-zes-08-p.1008290')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1008290') AND storage_key <> 'catalog/eraser/pentel_hipolymer_zes08_2pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/eraser/pentel_hipolymer_zes08_2pack.jpg', true, 'ยางลบดินสอ (2 ก้อน/แพ็ค) เพนเทล Hi-Polymer ZES-08' FROM products WHERE sku = 'b2s_1008290'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1006045
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1006045', 'เทปลบคำผิด 5มมx6ม. คละสี ฟาสเตอร์ C-649', 'correction_tape', 'Faster', '{"category_th": "เทปลบคำผิด", "group": "ยางลบและน้ำยาลบคำผิด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1006045.jpg"}'::jsonb, 45.00, 'THB', 'https://www.b2s.co.th/product/เทปลบคำผิด-5มมx6ม-คละสี-ฟาสเตอร์-c-649-p.1006045')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1006045') AND storage_key <> 'catalog/correction_tape/faster_c649_correction_tape.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/correction_tape/faster_c649_correction_tape.jpg', true, 'เทปลบคำผิด 5มมx6ม. คละสี ฟาสเตอร์ C-649' FROM products WHERE sku = 'b2s_1006045'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1091150
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1091150', 'เทปลบคำผิด พลัส รุ่น WH-1205 สีขาว', 'correction_tape', 'Plus', '{"category_th": "เทปลบคำผิด", "group": "ยางลบและน้ำยาลบคำผิด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1091150.jpg"}'::jsonb, 49.00, 'THB', 'https://www.b2s.co.th/product/เทปลบคำผิด-พลัส-รุ่น-wh-1205-สีขาว-p.1091150')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1091150') AND storage_key <> 'catalog/correction_tape/plus_wh1205_correction_tape_white.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/correction_tape/plus_wh1205_correction_tape_white.jpg', true, 'เทปลบคำผิด พลัส รุ่น WH-1205 สีขาว' FROM products WHERE sku = 'b2s_1091150'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_5096597
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_5096597', 'สมุดบันทึก MAYFLOWERN รุ่น NH-C.11 สีดำ', 'notebook', 'Mayflower', '{"category_th": "สมุด", "group": "กระดาษ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/5096597.jpg"}'::jsonb, 30.00, 'THB', 'https://www.b2s.co.th/product/สมุดบันทึก-mayflowern-รุ่น-nh-c-11-สีดำ-p.5096597')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_5096597') AND storage_key <> 'catalog/notebook/mayflower_nh_c11_notebook_black.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/notebook/mayflower_nh_c11_notebook_black.jpg', true, 'สมุดบันทึก MAYFLOWERN รุ่น NH-C.11 สีดำ' FROM products WHERE sku = 'b2s_5096597'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_5096405
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_5096405', 'สมุดโน๊ต Ropamoda  120แกรม 0739024แผ่น A4', 'notebook', 'Ropamoda', '{"category_th": "สมุด", "group": "กระดาษ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/5096405.jpeg"}'::jsonb, 195.00, 'THB', 'https://www.b2s.co.th/product/สมุดโน๊ต-ropamoda-120แกรม-0739024แผ่น-a4-p.5096405')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_5096405') AND storage_key <> 'catalog/notebook/ropamoda_notebook_a4_120g.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/notebook/ropamoda_notebook_a4_120g.jpg', true, 'สมุดโน๊ต Ropamoda  120แกรม 0739024แผ่น A4' FROM products WHERE sku = 'b2s_5096405'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_5096875
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_5096875', 'กระดาษโน้ตกาวในตัว ME.STYLE BELLA 2-B', 'sticky_note', 'ME.STYLE', '{"category_th": "กระดาษโน้ตกาว", "group": "กระดาษ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/5096875.jpg"}'::jsonb, 39.00, 'THB', 'https://www.b2s.co.th/product/กระดาษโน้ตกาวในตัว-me-style-bella-2-b-p.5096875')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_5096875') AND storage_key <> 'catalog/sticky_note/mestyle_bella_sticky_note_2b.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/sticky_note/mestyle_bella_sticky_note_2b.jpg', true, 'กระดาษโน้ตกาวในตัว ME.STYLE BELLA 2-B' FROM products WHERE sku = 'b2s_5096875'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_5096929
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_5096929', 'ME.STYLE ชุดกระดาษโน้ตกาวในตัว รุ่น STRAWBERRY 1-B สีชมพู', 'sticky_note', 'ME.STYLE', '{"category_th": "กระดาษโน้ตกาว", "group": "กระดาษ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/5096929.jpg"}'::jsonb, 39.00, 'THB', 'https://www.b2s.co.th/product/me-style-ชุดกระดาษโน้ตกาวในตัว-รุ่น-strawberry-1-b-สีชมพู-p.5096929')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_5096929') AND storage_key <> 'catalog/sticky_note/mestyle_strawberry_sticky_note_1b.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/sticky_note/mestyle_strawberry_sticky_note_1b.jpg', true, 'ME.STYLE ชุดกระดาษโน้ตกาวในตัว รุ่น STRAWBERRY 1-B สีชมพู' FROM products WHERE sku = 'b2s_5096929'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_5096930
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_5096930', 'ME.STYLE ชุดกระดาษโน้ตกาวในตัว รุ่น STRAWBERRY 2-B สีขาว-ชมพู', 'sticky_note', 'ME.STYLE', '{"category_th": "กระดาษโน้ตกาว", "group": "กระดาษ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/5096930.jpg"}'::jsonb, 39.00, 'THB', 'https://www.b2s.co.th/product/me-style-ชุดกระดาษโน้ตกาวในตัว-รุ่น-strawberry-2-b-สีขาว-ชมพู-p.5096930')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_5096930') AND storage_key <> 'catalog/sticky_note/mestyle_strawberry_sticky_note_2b.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/sticky_note/mestyle_strawberry_sticky_note_2b.jpg', true, 'ME.STYLE ชุดกระดาษโน้ตกาวในตัว รุ่น STRAWBERRY 2-B สีขาว-ชมพู' FROM products WHERE sku = 'b2s_5096930'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1092396
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1092396', 'ไม้บรรทัดฟุตเหล็ก INCA ขนาด 18 นิ้ว', 'ruler', 'INCA', '{"category_th": "ไม้บรรทัด", "group": "อุปกรณ์วัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1092396.jpg"}'::jsonb, 91.00, 'THB', 'https://www.b2s.co.th/product/ไม้บรรทัดฟุตเหล็ก-inca-ขนาด-18-นิ้ว-p.1092396')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1092396') AND storage_key <> 'catalog/ruler/inca_ruler_steel_18in.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/ruler/inca_ruler_steel_18in.jpg', true, 'ไม้บรรทัดฟุตเหล็ก INCA ขนาด 18 นิ้ว' FROM products WHERE sku = 'b2s_1092396'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_1091301
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_1091301', 'ไม้บรรทัดพลาสติก พี.เค. สีใส 12นิ้ว #022', 'ruler', 'P.K.', '{"category_th": "ไม้บรรทัด", "group": "อุปกรณ์วัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/1091301.png"}'::jsonb, 4.00, 'THB', 'https://www.b2s.co.th/product/ไม้บรรทัดพลาสติก-พี-เค-สีใส-12นิ้ว-022-p.1091301')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_1091301') AND storage_key <> 'catalog/ruler/pk_ruler_plastic_12in_022.png';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/ruler/pk_ruler_plastic_12in_022.png', true, 'ไม้บรรทัดพลาสติก พี.เค. สีใส 12นิ้ว #022' FROM products WHERE sku = 'b2s_1091301'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K090972
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K090972', 'ชุดวงเวียน MAPED 3 ชิ้นโลหะพิเศษ', 'compass', 'Maped', '{"category_th": "วงเวียน", "group": "อุปกรณ์วัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K090972.jpg"}'::jsonb, 107.00, 'THB', 'https://www.b2s.co.th/product/ชุดวงเวียน-maped-3-ชิ้นโลหะพิเศษ-p.K090972')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K090972') AND storage_key <> 'catalog/compass/maped_compass_set_3pcs.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/compass/maped_compass_set_3pcs.jpg', true, 'ชุดวงเวียน MAPED 3 ชิ้นโลหะพิเศษ' FROM products WHERE sku = 'b2s_K090972'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K090974
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K090974', 'วงเวียน MAPED GRAPHIC', 'compass', 'Maped', '{"category_th": "วงเวียน", "group": "อุปกรณ์วัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K090974.jpg"}'::jsonb, 62.00, 'THB', 'https://www.b2s.co.th/product/วงเวียน-maped-graphic-p.K090974')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K090974') AND storage_key <> 'catalog/compass/maped_graphic_compass.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/compass/maped_graphic_compass.jpg', true, 'วงเวียน MAPED GRAPHIC' FROM products WHERE sku = 'b2s_K090974'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K090929
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K090929', 'ชุดวงเวียนพลาสติก RADIUS สีฟ้า', 'compass', 'Radius', '{"category_th": "วงเวียน", "group": "อุปกรณ์วัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K090929.jpg"}'::jsonb, 95.00, 'THB', 'https://www.b2s.co.th/product/ชุดวงเวียนพลาสติก-radius-สีฟ้า-p.K090929')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K090929') AND storage_key <> 'catalog/compass/radius_compass_set_blue.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/compass/radius_compass_set_blue.jpg', true, 'ชุดวงเวียนพลาสติก RADIUS สีฟ้า' FROM products WHERE sku = 'b2s_K090929'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_2071790
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_2071790', 'SCOTCH กรรไกร รุ่น Precision 1448 สีแดง-เทา 8 นิ้ว', 'scissors', 'Scotch', '{"category_th": "กรรไกร", "group": "อุปกรณ์ตัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/2071790.jpg"}'::jsonb, 235.00, 'THB', 'https://www.b2s.co.th/product/scotch-กรรไกร-รุ่น-precision-1448-สีแดง-เทา-8-นิ้ว-p.2071790')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_2071790') AND storage_key <> 'catalog/scissors/scotch_precision_1448_8in.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/scissors/scotch_precision_1448_8in.jpg', true, 'SCOTCH กรรไกร รุ่น Precision 1448 สีแดง-เทา 8 นิ้ว' FROM products WHERE sku = 'b2s_2071790'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_2072020
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_2072020', 'กรรไกร 8 นิ้ว สก๊อตช์ Precision Ultra Edge 1468TUNS', 'scissors', 'Scotch', '{"category_th": "กรรไกร", "group": "อุปกรณ์ตัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/2072020.jpg"}'::jsonb, 295.00, 'THB', 'https://www.b2s.co.th/product/กรรไกร-8-นิ้ว-สก๊อตช์-precision-ultra-edge-1468tuns-p.2072020')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_2072020') AND storage_key <> 'catalog/scissors/scotch_precision_ultra_edge_1468tuns_8in.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/scissors/scotch_precision_ultra_edge_1468tuns_8in.jpg', true, 'กรรไกร 8 นิ้ว สก๊อตช์ Precision Ultra Edge 1468TUNS' FROM products WHERE sku = 'b2s_2072020'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_2003432
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_2003432', 'มีดคัตเตอร์ 45L ดำ สก๊อตช์ XP002024089', 'cutter', 'Scotch', '{"category_th": "คัตเตอร์", "group": "อุปกรณ์ตัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/2003432.jpg"}'::jsonb, 135.00, 'THB', 'https://www.b2s.co.th/product/มีดคัตเตอร์-45l-ดำ-สก๊อตช์-xp002024089-p.2003432')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_2003432') AND storage_key <> 'catalog/cutter/scotch_cutter_45l_black.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/cutter/scotch_cutter_45l_black.jpg', true, 'มีดคัตเตอร์ 45L ดำ สก๊อตช์ XP002024089' FROM products WHERE sku = 'b2s_2003432'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_2002894
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_2002894', 'มีดคัตเตอร์ ไทเทเนียม 3M Size L Scotch XP002015285', 'cutter', 'Scotch', '{"category_th": "คัตเตอร์", "group": "อุปกรณ์ตัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/2002894.jpg"}'::jsonb, 199.00, 'THB', 'https://www.b2s.co.th/product/มีดคัตเตอร์-ไทเทเนียม-3m-size-l-scotch-xp002015285-p.2002894')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_2002894') AND storage_key <> 'catalog/cutter/scotch_titanium_cutter_l.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/cutter/scotch_titanium_cutter_l.jpg', true, 'มีดคัตเตอร์ ไทเทเนียม 3M Size L Scotch XP002015285' FROM products WHERE sku = 'b2s_2002894'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_2003391
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_2003391', 'มีดคัตเตอร์อเนกประสงค์ ขาว SDI 0443C', 'cutter', 'SDI', '{"category_th": "คัตเตอร์", "group": "อุปกรณ์ตัด", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/2003391.jpg"}'::jsonb, 145.00, 'THB', 'https://www.b2s.co.th/product/มีดคัตเตอร์อเนกประสงค์-ขาว-sdi-0443c-p.2003391')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_2003391') AND storage_key <> 'catalog/cutter/sdi_0443c_cutter_white.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/cutter/sdi_0443c_cutter_white.jpg', true, 'มีดคัตเตอร์อเนกประสงค์ ขาว SDI 0443C' FROM products WHERE sku = 'b2s_2003391'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_3090269
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_3090269', 'กาวแท่ง เอลเมอร์  เนื้อกาวขาว 8กรัม', 'glue', 'Elmer''s', '{"category_th": "กาว", "group": "กาว & เทป", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/3090269.jpg"}'::jsonb, 33.00, 'THB', 'https://www.b2s.co.th/product/กาวแท่ง-เอลเมอร์-เนื้อกาวขาว-8กรัม-p.3090269')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_3090269') AND storage_key <> 'catalog/glue/elmers_glue_stick_8g.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/glue/elmers_glue_stick_8g.jpg', true, 'กาวแท่ง เอลเมอร์  เนื้อกาวขาว 8กรัม' FROM products WHERE sku = 'b2s_3090269'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K091913
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K091913', 'MONT MARTE กาวน้ำ ขนาด 147 มล.', 'glue', 'Mont Marte', '{"category_th": "กาว", "group": "กาว & เทป", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K091913.jpg"}'::jsonb, 112.00, 'THB', 'https://www.b2s.co.th/product/mont-marte-กาวน้ำ-ขนาด-147-มล-p.K091913')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K091913') AND storage_key <> 'catalog/glue/montmarte_liquid_glue_147ml.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/glue/montmarte_liquid_glue_147ml.jpg', true, 'MONT MARTE กาวน้ำ ขนาด 147 มล.' FROM products WHERE sku = 'b2s_K091913'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_3011150
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_3011150', 'กาวแท่ง 7.08 กรัม ขาว สก๊อตช์ 6008', 'glue', 'Scotch', '{"category_th": "กาว", "group": "กาว & เทป", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/3011150.jpg"}'::jsonb, 29.00, 'THB', 'https://www.b2s.co.th/product/กาวแท่ง-7-08-กรัม-ขาว-สก๊อตช์-6008-p.3011150')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_3011150') AND storage_key <> 'catalog/glue/scotch_6008_glue_stick_7g.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/glue/scotch_6008_glue_stick_7g.jpg', true, 'กาวแท่ง 7.08 กรัม ขาว สก๊อตช์ 6008' FROM products WHERE sku = 'b2s_3011150'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_3101210
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_3101210', 'SCOTCH เทปใส รุ่น 500 ขนาด 1/2 นิ้ว x 36 หลา แกน 1 นิ้ว (แพ็ค 9 ม้วน)', 'clear_tape', 'Scotch', '{"category_th": "เทปใส", "group": "กาว & เทป", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/3101210.jpg"}'::jsonb, 214.00, 'THB', 'https://www.b2s.co.th/product/scotch-เทปใส-รุ่น-500-ขนาด-1-2-นิ้ว-x-36-หลา-แกน-1-นิ้ว-แพ็ค-9-ม้วน-p.3101210')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_3101210') AND storage_key <> 'catalog/clear_tape/scotch_500_clear_tape_1_2in_9pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/clear_tape/scotch_500_clear_tape_1_2in_9pack.jpg', true, 'SCOTCH เทปใส รุ่น 500 ขนาด 1/2 นิ้ว x 36 หลา แกน 1 นิ้ว (แพ็ค 9 ม้วน)' FROM products WHERE sku = 'b2s_3101210'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_3090256
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_3090256', 'SCOTCH เทปใส รุ่น 500 แกน 1 นิ้ว ขนาด 1" x 36 หลา แพ็ค 7 ม้วน', 'clear_tape', 'Scotch', '{"category_th": "เทปใส", "group": "กาว & เทป", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/3090256.jpg"}'::jsonb, 266.00, 'THB', 'https://www.b2s.co.th/product/scotch-เทปใส-รุ่น-500-แกน-1-นิ้ว-ขนาด-1-x-36-หลา-แพ็ค-7-ม้วน-p.3090256')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_3090256') AND storage_key <> 'catalog/clear_tape/scotch_500_clear_tape_1in_7pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/clear_tape/scotch_500_clear_tape_1in_7pack.jpg', true, 'SCOTCH เทปใส รุ่น 500 แกน 1 นิ้ว ขนาด 1" x 36 หลา แพ็ค 7 ม้วน' FROM products WHERE sku = 'b2s_3090256'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_3101160
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_3101160', 'SCOTCH เทปใส รุ่น 500 แกน 1 นิ้ว ขนาด 3/4 นิ้ว x 36 หลา (แพ็ค 6 ม้วน)', 'clear_tape', 'Scotch', '{"category_th": "เทปใส", "group": "กาว & เทป", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/3101160.jpg"}'::jsonb, 226.00, 'THB', 'https://www.b2s.co.th/product/scotch-เทปใส-รุ่น-500-แกน-1-นิ้ว-ขนาด-3-4-นิ้ว-x-36-หลา-แพ็ค-6-ม้วน-p.3101160')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_3101160') AND storage_key <> 'catalog/clear_tape/scotch_500_clear_tape_3_4in_6pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/clear_tape/scotch_500_clear_tape_3_4in_6pack.jpg', true, 'SCOTCH เทปใส รุ่น 500 แกน 1 นิ้ว ขนาด 3/4 นิ้ว x 36 หลา (แพ็ค 6 ม้วน)' FROM products WHERE sku = 'b2s_3101160'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K091420
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K091420', 'สีไม้ระบายน้ำ FABER CASTELL  48 สี', 'colored_pencil', 'Faber-Castell', '{"category_th": "ดินสอสี", "group": "ศิลปะและงานฝีมือ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K091420.png"}'::jsonb, 595.00, 'THB', 'https://www.b2s.co.th/product/สีไม้ระบายน้ำ-faber-castell-48-สี-p.K091420')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K091420') AND storage_key <> 'catalog/colored_pencil/fabercastell_watercolor_pencil_48colors.png';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/colored_pencil/fabercastell_watercolor_pencil_48colors.png', true, 'สีไม้ระบายน้ำ FABER CASTELL  48 สี' FROM products WHERE sku = 'b2s_K091420'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_K091454
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_K091454', 'สีไม้ MAPED รุ่น COLOR''PEPS 12 สี', 'colored_pencil', 'Maped', '{"category_th": "ดินสอสี", "group": "ศิลปะและงานฝีมือ", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-27", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/K091454.jpg"}'::jsonb, 178.00, 'THB', 'https://www.b2s.co.th/product/สีไม้-maped-รุ่น-colorpeps-12-สี-p.K091454')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_K091454') AND storage_key <> 'catalog/colored_pencil/maped_colorpeps_12colors.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/colored_pencil/maped_colorpeps_12colors.jpg', true, 'สีไม้ MAPED รุ่น COLOR''PEPS 12 สี' FROM products WHERE sku = 'b2s_K091454'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_6092770
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_6092770', 'แฟ้มซองพลาสติก ไบน์เดอร์แม็กซ์ BB-4002 สีคละสี F4 (12ซอง/แพ็ค)', 'file_folder', 'BinderMax', '{"category_th": "แฟ้มเอกสาร", "group": "แฟ้ม และ ซองเอกสาร", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/6092770.png"}'::jsonb, 92.00, 'THB', 'https://www.b2s.co.th/product/แฟ้มซองพลาสติก-ไบน์เดอร์แม็กซ์-bb-4002-สีคละสี-f4-12ซอง-แพ็ค-p.6092770')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_6092770') AND storage_key <> 'catalog/file_folder/bindermax_bb4002_envelope_f4_12pack.png';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/file_folder/bindermax_bb4002_envelope_f4_12pack.png', true, 'แฟ้มซองพลาสติก ไบน์เดอร์แม็กซ์ BB-4002 สีคละสี F4 (12ซอง/แพ็ค)' FROM products WHERE sku = 'b2s_6092770'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_6005239
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_6005239', 'ELEPHANT แฟ้มสันกว้าง รุ่น 2100F ขนาด F4 สัน 3 นิ้ว สีพีช (ชมพูพาสเทล)', 'file_folder', 'Elephant', '{"category_th": "แฟ้มเอกสาร", "group": "แฟ้ม และ ซองเอกสาร", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/6005239.jpg"}'::jsonb, 115.00, 'THB', 'https://www.b2s.co.th/product/elephant-แฟ้มสันกว้าง-รุ่น-2100f-ขนาด-f4-สัน-3-นิ้ว-สีพีช-ชมพูพาสเทล-p.6005239')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_6005239') AND storage_key <> 'catalog/file_folder/elephant_2100f_lever_arch_f4_peach.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/file_folder/elephant_2100f_lever_arch_f4_peach.jpg', true, 'ELEPHANT แฟ้มสันกว้าง รุ่น 2100F ขนาด F4 สัน 3 นิ้ว สีพีช (ชมพูพาสเทล)' FROM products WHERE sku = 'b2s_6005239'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

-- b2s_6092689
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ('b2s_6092689', 'แฟ้มซองพลาสติกผูกเชือก A4 ONE สีขาวใส ขนาด 26 x 33 ซม. (6 ซอง/แพ็ค)', 'file_folder', 'ONE', '{"category_th": "แฟ้มเอกสาร", "group": "แฟ้ม และ ซองเอกสาร", "license": "© B2S/OfficeMate - educational use only", "price_date": "2026-09-28", "source_image_url": "https://pim-cdn0.ofm.co.th/products/large/6092689.jpg"}'::jsonb, 31.00, 'THB', 'https://www.b2s.co.th/product/แฟ้มซองพลาสติกผูกเชือก-a4-one-สีขาวใส-ขนาด-26-x-33-ซม-6-ซอง-แพ็ค-p.6092689')
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = 'b2s_6092689') AND storage_key <> 'catalog/file_folder/one_string_envelope_a4_6pack.jpg';
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, 'catalog/file_folder/one_string_envelope_a4_6pack.jpg', true, 'แฟ้มซองพลาสติกผูกเชือก A4 ONE สีขาวใส ขนาด 26 x 33 ซม. (6 ซอง/แพ็ค)' FROM products WHERE sku = 'b2s_6092689'
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;

COMMIT;
