"""Generate database/seed/001_catalog_products.sql from backend/datasets/catalog/metadata.csv.

Run from the repository root with the backend virtualenv:

    backend/.venv/Scripts/python database/seed/generate_catalog_seed.py

The CSV is validated with the same loader the backend uses. Rows with errors
abort generation. Values the catalog does not have (description, availability)
stay NULL — they are never invented.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "backend"))

from app.ai.rag.indexing_service import CatalogProduct, load_catalog  # noqa: E402  # pyright: ignore[reportMissingImports]

CATALOG_DIR = REPO / "backend" / "datasets" / "catalog"
OUT = Path(__file__).with_name("001_catalog_products.sql")
CURRENCY = "THB"
# storage_key is relative to the image storage root (currently backend/datasets/)
STORAGE_PREFIX = "catalog/"


def q(value: str | None) -> str:
    """SQL string literal (standard_conforming_strings: only quotes need escaping)."""
    return "NULL" if value is None else "'" + value.replace("'", "''") + "'"


def attributes(p: CatalogProduct) -> dict:
    attrs = {
        "category_th": p.category_th,
        "group": p.group,
        "unit": p.unit,
        "pack_qty": p.pack_qty,
        "color": p.color or None,
        "size": p.size or None,
        "price_date": p.price_date.isoformat(),
        "source_image_url": p.image_url or None,
        "license": p.license or None,
        "catalog_note": p.notes or None,
    }
    return {k: v for k, v in attrs.items() if v is not None}


def product_sql(p: CatalogProduct) -> str:
    attrs = json.dumps(attributes(p), ensure_ascii=False, sort_keys=True)
    storage_key = STORAGE_PREFIX + p.filename
    return f"""-- {p.sku}
INSERT INTO products (sku, name, category, brand, attributes, price, currency, source_ref)
VALUES ({q(p.sku)}, {q(p.name)}, {q(p.category)}, {q(p.brand_norm)}, {q(attrs)}::jsonb, {p.price_thb:.2f}, {q(CURRENCY)}, {q(p.source_url)})
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name, category = EXCLUDED.category, brand = EXCLUDED.brand,
    attributes = EXCLUDED.attributes, price = EXCLUDED.price, currency = EXCLUDED.currency,
    source_ref = EXCLUDED.source_ref, updated_at = now();
UPDATE product_images SET is_primary = false
WHERE product_id = (SELECT id FROM products WHERE sku = {q(p.sku)}) AND storage_key <> {q(storage_key)};
INSERT INTO product_images (product_id, storage_key, is_primary, alt_text)
SELECT id, {q(storage_key)}, true, {q(p.name)} FROM products WHERE sku = {q(p.sku)}
ON CONFLICT (storage_key) DO UPDATE SET
    product_id = EXCLUDED.product_id, is_primary = true, alt_text = EXCLUDED.alt_text;
"""


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    products, report = load_catalog(CATALOG_DIR, strict=True)
    active = [p for p in products if p.is_active]
    header = f"""-- Catalog seed: products + primary product_images.
-- GENERATED by database/seed/generate_catalog_seed.py from backend/datasets/catalog/metadata.csv.
-- Do not edit by hand; change the CSV and regenerate. Safe to run repeatedly (upserts).
-- description and availability are left NULL: the catalog has no verified values for them.
-- Products: {len(active)}

BEGIN;

"""
    OUT.write_text(header + "\n".join(product_sql(p) for p in active) + "\nCOMMIT;\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(active)} products, {len(products) - len(active)} inactive skipped)")
    for w in report.warnings:
        print(f"  WARNING {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
